catalogo_productos/apps/favoritos/urls.py
from django.urls import path

from . import views

app_name= "favoritos"

urlpatterns = [
    path('agregar/<int:producto_id>/', views.agregar_favorito, name='agregar_favorito'),
    path('quitar/<int:producto_id>/', views.quitar_favorito, name='quitar_favorito'),
    path('listar/', views.Listar.as_view(), name='listar'),
    path('quitar_detalle/<int:producto_id>/', views.quitar_favorito_detalle, name='quitar_favorito_detalle'),
]

catalogo_productos/apps/productos/urls.py
from django.urls import path

from . import views

app_name = "productos"

urlpatterns = [
    path('listar/', views.Listar.as_view(), name='listar'),
    path('listar-categorias/', views.ListarCategorias.as_view(), name='listar_categorias'),
    path('nuevo/', views.Nuevo.as_view(), name='nuevo'),
    path('nueva-categoria/', views.NuevaCategoria.as_view(), name='nueva_categoria'),
    path('editar/<int:pk>/', views.Editar.as_view(), name='editar'),
    path('editar-categoria/<int:pk>/', views.EditarCategoria.as_view(), name='editar_categoria'),
    path('eliminar/<int:pk>/', views.Eliminar.as_view(), name='eliminar'),
    path('eliminar-categoria/<int:pk>/', views.EliminarCategoria.as_view(), name='eliminar_categoria'),
    path('detalle-producto/<int:pk>/', views.ViewProducto.as_view(), name='ver_detalle'),
    path('desactivar-producto/<int:pk>/,', views.Desactivar.as_view(), name='desactivar')
]

catalogo_productos/apps/usuarios/urls.py
from django.urls import path
from .views import PerfilUsuario, EditarPerfil

from . import views

app_name = "usuarios"

urlpatterns = [
    path('listar-todos/', views.listar_usuarios, name='listar_todos'),
    path('perfil/', PerfilUsuario.as_view(), name='perfil'),
    path('perfil/editar/', EditarPerfil.as_view(), name='editar_perfil'),
]

catalogo_productos/catalogo_productos/urls.py
from django.contrib import admin
from django.contrib.auth import views as views_django
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='pagina_principal'),
    path('registrarme/', views.registrarme, name="registrarme"),
    path('error-permisos/', views.pagina_error_permisos, name="error_permisos"),

    # Login & Logout
    path('login/', views_django.LoginView.as_view(template_name="login.html"), name="iniciar_sesion"),
    path('logout/', views_django.logout_then_login, name="cerrar_sesion"),
    
    # Includes
    path("usuarios/", include('apps.usuarios.urls')),
    path("productos/", include('apps.productos.urls')),
    path("favoritos/", include('apps.favoritos.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalogo_productos/templates/base/barra_navegacion.html
<div class="offcanvas-body d-md-flex flex-column p-0 pt-lg-3 overflow-y-auto">

    <ul class="nav flex-column">

        {% if user.is_authenticated and user.es_admin %}

        <li class="nav-item">
            <a class="nav-link d-flex align-items-center gap-2 active" aria-current="page" href="{% url 'usuarios:listar_todos' %}">
                <i class="fas fa-users"></i>
                LISTA DE USUARIOS
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link d-flex align-items-center gap-2 active" aria-current="page" href="{% url 'productos:listar' %}">
                <i class="fa-solid fa-cart-shopping"></i>
                LISTA DE PRODUCTOS
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link d-flex align-items-center gap-2 active" aria-current="page" href="{% url 'favoritos:listar' %}">
                <i class="fa-solid fa-star"></i>
                LISTA DE FAVORITOS
            </a>
        </li>

        {% else %} <!-- OSEA, SI ESTA AUTENTICADO O ES UN USUARIO SIN REGISTRARSE -->

        <li class="nav-item">
            <a class="nav-link d-flex align-items-center gap-2 active" aria-current="page" href="{% url 'productos:listar' %}">
                <i class="fa-solid fa-cart-shopping"></i>
                LISTA DE PRODUCTOS
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link d-flex align-items-center gap-2 active" aria-current="page" href="{% url 'favoritos:listar' %}">
                <i class="fa-solid fa-star"></i>
                LISTA DE FAVORITOS
            </a>
        </li>

        {% endif %}
        
    </ul>

    

    <hr class="my-3">
    
    <ul class="nav flex-column mb-auto">

        {% if not user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link d-flex align-items-center gap-2 active" aria-current="page" href="{% url 'registrarme' %}">
                <i class="fas fa-user-plus"></i> REGISTRARME
            </a>
        </li>
        {% endif %}

        <li class="nav-item">
    
            {% if user.is_authenticated %}

            <li class="nav-item">
                <a class="nav-link d-flex align-items-center gap-2 active" aria-current="page" href="{% url 'usuarios:perfil' %}">
                    <i class="fa-solid fa-user-pen"></i>
                    MIS DATOS PERSONALES
                </a>
            </li>
            <br class="my-3">
            
            <form action="{% url 'cerrar_sesion' %}" method="post">{% csrf_token %}

                <button class="nav-link d-flex align-items-center gap-2 bi" type="submit"
                style="text-transform: uppercase;">SALIR ({{user.username}}) </button>

            </form>

            {% else %}

            <a class="nav-link d-flex align-items-center gap-2" href="{% url 'iniciar_sesion' %}">
                
                <i class="fa-solid fa-right-to-bracket"></i> INICIAR SESIÓN
            </a>

            {% endif %}


        </li>
    </ul>

</div>

catalogo_productos/templates/base/base.html
{% load static %}

<html lang="en" data-bs-theme="light">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.122.0">
    <title>INICIO - GESTIÓN DE CATÁLOGO DE PRODUCTOS</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <!-- Clase 09: 59.00 -> Mirar Continua -->
    <!-- <link href="https://getbootstrap.com/docs/5.3/examples/dashboard/dashboard.css" rel="stylesheet"> -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">

    
    {% block css_extras %}
        
    {% endblock css_extras %}
        
</head>

<body>

    {% include 'base/header.html' %}

    <div class="container-fluid">
        <div class="row">
            <div class="sidebar border border-right col-md-3 col-lg-2 p-0 bg-body-tertiary">
                <div class="offcanvas-md offcanvas-end bg-body-tertiary" tabindex="-1" id="sidebarMenu"
                    aria-labelledby="sidebarMenuLabel">
                    <div class="offcanvas-header">
                        <h5 class="offcanvas-title" id="sidebarMenuLabel">GESTIÓN DE CATÁLOGO DE PRODUCTOS</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="offcanvas"
                            data-bs-target="#sidebarMenu" aria-label="Close"></button>
                    </div>

                    <!-- BARRA DE NAVEGACION LATERAL -->
                    {% include 'base/barra_navegacion.html' %}
                </div>
            </div>

            <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">


                {% block contenido %}

                {% endblock contenido %}
            </main>
        </div>
    </div>

    <script
  src="https://code.jquery.com/jquery-3.7.1.min.js"
  integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
  crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.js"></script>

    
    {% block js_extras %}
        
    {% endblock js_extras %}
        
</body>

</html>

catalogo_productos/templates/base/header.html
<header class="navbar sticky-top bg-dark flex-md-nowrap p-0 shadow" data-bs-theme="dark">
    <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6 text-white" href="{% url 'pagina_principal' %}">GESTIÓN
        DE UN CATÁLOGO DE PRODUCTOS</a>
</header>