catalogo_productos/apps/favoritos/urls.py
from django.urls import path

from . import views

app_name= "favoritos"

urlpatterns = [
    path('agregar/<int:producto_id>/', views.agregar_favorito, name='agregar_favorito'),
    path('quitar/<int:producto_id>/', views.quitar_favorito, name='quitar_favorito'),
    path('listar/', views.Listar.as_view(), name='listar'),
    path('quitar_detalle/<int:producto_id>/', views.quitar_favorito_detalle, name='quitar_favorito_detalle'),
]

catalogo_productos/catalogo_productos/urls.py
from django.contrib import admin
from django.contrib.auth import views as views_django
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='pagina_principal'),
    path('registrarme/', views.registrarme, name="registrarme"),
    path('error-permisos/', views.pagina_error_permisos, name="error_permisos"),

    # Login & Logout
    path('login/', views_django.LoginView.as_view(template_name="login.html"), name="iniciar_sesion"),
    path('logout/', views_django.logout_then_login, name="cerrar_sesion"),
    
    # Includes
    path("usuarios/", include('apps.usuarios.urls')),
    path("productos/", include('apps.productos.urls')),
    path("favoritos/", include('apps.favoritos.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalogo_productos/apps/favoritos/models.py
from django.db import models

# Create your models here.

from apps.usuarios.models import Usuario
from apps.productos.models import Producto

class Favorito(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('usuario', 'producto')

catalogo_productos/apps/favoritos/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView

from apps.utils.decorators import verificar_favorito

from .models import Favorito

# Create your views here.

class Listar(LoginRequiredMixin, ListView):
    template_name='favoritos/listar.html'
    model = Favorito
    context_object_name = 'favoritos'
    paginate_by = 20

    def get_queryset(self):
        return Favorito.objects.filter(usuario=self.request.user)

@verificar_favorito()
def agregar_favorito(request, producto_id):
    if request.method == 'POST':
        # Verificar si el producto ya está en la lista de favoritos
        if Favorito.objects.filter(usuario=request.user, producto_id=producto_id).exists():
            messages.warning(request, 'Este producto ya está en tu lista de favoritos.')
        else:
            Favorito.objects.create(usuario=request.user, producto_id=producto_id)
            messages.success(request, 'Producto agregado a favoritos exitosamente.')

    return redirect('productos:listar')

@verificar_favorito()
def quitar_favorito(request, producto_id):
    if request.method == 'POST':
        # Verificar si el producto está en la lista de favoritos del usuario
        if Favorito.objects.filter(usuario=request.user, producto_id=producto_id).exists():
            Favorito.objects.filter(usuario=request.user, producto_id=producto_id).delete()
            messages.success(request, 'Producto eliminado de favoritos exitosamente.')
        else:
            messages.error(request, 'El producto no está en la lista de favoritos.')
    return redirect('productos:listar')

@verificar_favorito()
def quitar_favorito_detalle(request, producto_id):
    if request.method == 'POST':
        if Favorito.objects.filter(usuario=request.user, producto_id=producto_id).exists():
            Favorito.objects.filter(usuario=request.user, producto_id=producto_id).delete()
            messages.success(request, 'Producto eliminado de favoritos exitosamente.')
    return redirect('favoritos:listar')

catalogo_productos/templates/favoritos/listar.html
{% extends 'base/base.html' %}

{% block contenido %}

	<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">

		<h1 class="h2">LISTA DE PRODUCTOS</h1>
		{% if messages %}

		<div class="alert alert-success" role="alert">
			<ul>
				{% for message in messages %}
					<strong>{{message}}</strong>
				{% endfor %}
			</ul>
		</div>
		
		{% endif %}

	</div>
	<div class="row">

		<div class="col">
			<table class="table table-striped">
				<thead>
					<tr>
						<th scope="col">Nombre</th>
						<th scope="col">Descripcion</th>
						<th scope="col">Precio</th>
						<th>Acciones</th>
					</tr>
				</thead>
				<tbody>

					{% for favorito in favoritos %}
						<div>
							<tr>
								<td>{{favorito.producto.nombre}}</td>
								<td>{{favorito.producto.descripcion}}</td>
								<td>{{favorito.producto.precio}}</td>
								<td>
									<form action="{% url 'favoritos:quitar_favorito_detalle' favorito.producto.pk %}" method="post">
										{% csrf_token %}
										<button type="submit" class="btn btn-danger btn-sm">Quitar de Favoritos</button>
									</form>

								</td>
								
							</tr>
						</div>
					{% endfor %}

				</tbody>

			</table>

		</div>
	</div>
{% endblock contenido %}