catalogo_productos/apps/favoritos/urls.py
from django.urls import path

from . import views

app_name= "favoritos"

urlpatterns = [
    path('agregar/<int:producto_id>/', views.agregar_favorito, name='agregar_favorito'),
    path('quitar/<int:producto_id>/', views.quitar_favorito, name='quitar_favorito'),
    path('listar/', views.Listar.as_view(), name='listar'),
    path('quitar_detalle/<int:producto_id>/', views.quitar_favorito_detalle, name='quitar_favorito_detalle'),
]

catalogo_productos/apps/productos/urls.py
from django.urls import path

from . import views

app_name = "productos"

urlpatterns = [
    path('listar/', views.Listar.as_view(), name='listar'),
    path('listar-categorias/', views.ListarCategorias.as_view(), name='listar_categorias'),
    path('nuevo/', views.Nuevo.as_view(), name='nuevo'),
    path('nueva-categoria/', views.NuevaCategoria.as_view(), name='nueva_categoria'),
    path('editar/<int:pk>/', views.Editar.as_view(), name='editar'),
    path('editar-categoria/<int:pk>/', views.EditarCategoria.as_view(), name='editar_categoria'),
    path('eliminar/<int:pk>/', views.Eliminar.as_view(), name='eliminar'),
    path('eliminar-categoria/<int:pk>/', views.EliminarCategoria.as_view(), name='eliminar_categoria'),
    path('detalle-producto/<int:pk>/', views.ViewProducto.as_view(), name='ver_detalle'),
    path('desactivar-producto/<int:pk>/,', views.Desactivar.as_view(), name='desactivar')
]

catalogo_productos/catalogo_productos/urls.py
from django.contrib import admin
from django.contrib.auth import views as views_django
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='pagina_principal'),
    path('registrarme/', views.registrarme, name="registrarme"),
    path('error-permisos/', views.pagina_error_permisos, name="error_permisos"),

    # Login & Logout
    path('login/', views_django.LoginView.as_view(template_name="login.html"), name="iniciar_sesion"),
    path('logout/', views_django.logout_then_login, name="cerrar_sesion"),
    
    # Includes
    path("usuarios/", include('apps.usuarios.urls')),
    path("productos/", include('apps.productos.urls')),
    path("favoritos/", include('apps.favoritos.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalogo_productos/apps/productos/models.py
from django.db import models

# Create your models here.

class Categoria(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre


class Producto(models.Model):
    nombre = models.CharField(max_length=255)
    categorias = models.ManyToManyField(Categoria)
    precio = models.DecimalField(max_digits=6, decimal_places=2)
    descripcion = models.TextField()
    activo = models.BooleanField(default=True)
    imagen = models.ImageField(null=True, blank=True, upload_to="productos_img/")

catalogo_productos/apps/productos/forms.py
from django import forms

from .models import Producto, Categoria

class ProductoForm(forms.ModelForm):
    categorias = forms.ModelMultipleChoiceField(
        queryset=Categoria.objects.all(),
        widget=forms.SelectMultiple()
    )

    nombre = forms.CharField(
        widget=forms.TextInput(attrs={'class' : 'form-control'})
    )

    descripcion = forms.CharField(
        widget=forms.Textarea(attrs={'class' : 'form-control'})
    )

    #activo = forms.???

    precio = forms.DecimalField(
        widget=forms.TextInput(attrs={'class' : 'form-control'})
    )

    class Meta:
        model = Producto
        fields = ["nombre", "categorias", "precio", "descripcion", "activo", "imagen"]


class CForm(forms.ModelForm):

    nombre = forms.CharField(
        widget=forms.TextInput(attrs={'class' : 'form-control'})
    )

    class Meta:
        model = Categoria
        fields = ["nombre"]

class VerForm(forms.ModelForm):

    categorias = forms.ModelMultipleChoiceField(
        queryset=Categoria.objects.all(),
        widget=forms.SelectMultiple(attrs={'disabled' : 'disabled'})
    )

    nombre = forms.CharField(
        widget=forms.TextInput(attrs={'disabled' : 'disabled', 'class' : 'form-control'})
    )

    descripcion = forms.CharField(
        widget=forms.Textarea(attrs={'disabled' : 'disabled', 'class' : 'form-control'})
    )

    activo = forms.BooleanField(
        widget=forms.CheckboxInput(attrs={'disabled' : 'disabled'})
    )

    precio = forms.DecimalField(
        widget=forms.TextInput(attrs={'disabled' : 'disabled', 'class' : 'form-control'})
    )

    class Meta:
        model = Producto
        fields = ["nombre", "categorias", "precio", "descripcion", "activo", "imagen"]

catalogo_productos/apps/productos/views.py
# Create your views here.
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin

from django_filters.views import FilterView

from apps.utils.mixins import VerificarAdmin

from .filterset import ProductoFilter

from .forms import ProductoForm, CForm, VerForm
from .models import Producto, Categoria
from apps.favoritos.models import Favorito

class Listar(FilterView):
    template_name='productos/listar.html'
    model = Producto
    context_object_name = 'productos'
    paginate_by = 20
    filterset_class=ProductoFilter

    def get_queryset(self):
        return self.model.objects.all().filter(activo = True).order_by("nombre")
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        productos = context['productos']

        # Creamos un lista para almacenar todos los favoritos del usuarios
        fpk = []

        if not self.request.user.is_anonymous:
            # Recorremos los favoritos del usuario actual y lo agregamos a la lista
            for f in Favorito.objects.filter(usuario=self.request.user, producto__in=productos):
                fpk.append(f.producto_id)

        context['Favoritos'] = fpk
        
        return context

class Nuevo(LoginRequiredMixin, VerificarAdmin, CreateView):
    template_name = "productos/crear.html"
    model = Producto
    form_class = ProductoForm
    success_url = reverse_lazy("productos:listar")


class ListarCategorias(LoginRequiredMixin, VerificarAdmin, ListView, ):
    template_name='productos/listar_categorias.html'
    model = Categoria
    context_object_name = 'categorias'
    paginate_by = 20

    def get_queryset(self):
        return self.model.objects.all().order_by("id")
    
class NuevaCategoria(LoginRequiredMixin, VerificarAdmin, CreateView):
    template_name = "productos/crear_categoria.html"
    model = Categoria
    form_class = CForm
    success_url = reverse_lazy("productos:listar_categorias")

class Editar(LoginRequiredMixin, VerificarAdmin, UpdateView):
    template_name = "productos/editar.html"
    model = Producto
    form_class = ProductoForm
    success_url = reverse_lazy("productos:listar")

class EditarCategoria(LoginRequiredMixin, VerificarAdmin, UpdateView):
    template_name = "productos/editar_categoria.html"
    model = Categoria
    form_class = CForm
    success_url = reverse_lazy("productos:listar_categorias")

class Eliminar(LoginRequiredMixin, VerificarAdmin, DeleteView):
    model = Producto
    success_url = reverse_lazy("productos:listar")

class EliminarCategoria(LoginRequiredMixin, VerificarAdmin, DeleteView):
    model = Categoria
    success_url = reverse_lazy("productos:listar_categorias")

class ViewProducto(UpdateView):
    template_name = "productos/ver_detalle.html"
    model = Producto
    form_class = VerForm
    success_url = reverse_lazy("productos:listar")

class Desactivar(LoginRequiredMixin, VerificarAdmin, DeleteView):
    model = Producto

    def post(self, request,pk, *args, **kwargs):
        object = Producto.objects.get(id = pk)
        object.activo = False
        object.save()
        return redirect("productos:listar")

catalogo_productos/templates/productos/categoria_confirm_delete.html
{% extends 'base/base.html' %}

{% block contenido %}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">            
    <h1 class="h2">Confirmar Eliminación de Categoría {{categoria.nombre}} </h1>                       
</div>

<form method="POST">{% csrf_token %}
    <p><strong>¿Desea eliminar el registro {{categoria.nombre}} ?</strong></p>
    <button type="submit" class="btn btn-danger">Confirmar</button>
</form>

{% endblock contenido %}

catalogo_productos/templates/productos/crear.html
{% extends 'base/base.html' %}


{% block css_extras %}
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
{% endblock css_extras %}


{% block contenido %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">            
        <h1 class="h2">Nuevo Producto</h1>                       
    </div>

    <form method="POST" enctype="multipart/form-data">{% csrf_token %}



        {{form.errors}}

        {{form.as_p}}

        <hr class="my-4">
        <button class="w-100 btn btn-primary btn-lg" type="submit">GUARDAR</button>


    </form>
{% endblock contenido %}



{% block js_extras %}
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script>
        $('#id_categorias').select2({
            width: '100%',
        });
    </script>
{% endblock js_extras %}

catalogo_productos/templates/productos/crear_categoria.html
{% extends 'base/base.html' %}


{% block css_extras %}
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
{% endblock css_extras %}


{% block contenido %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">            
        <h1 class="h2">Nueva Categoria</h1>                       
    </div>

    <form method="POST">{% csrf_token %}

        {{form.errors}}

        {{form.as_p}}

        <hr class="my-4">
        <button class="w-100 btn btn-primary btn-lg" type="submit">GUARDAR</button>


    </form>
{% endblock contenido %}



{% block js_extras %}
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script>
        $('#id_categorias').select2({
            width: '100%',
        });
    </script>
{% endblock js_extras %}

catalogo_productos/templates/productos/editar.html
{% extends 'base/base.html' %}


<!-- {% block css_extras %}
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
{% endblock css_extras %} -->


{% block contenido %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">            
        <h1 class="h2">Editar Producto</h1>                       
    </div>

    <form method="POST">{% csrf_token %}



        {{form.errors}}

        {{form.as_p}}

        <hr class="my-4">
        <button class="w-100 btn btn-primary btn-lg" type="submit">GUARDAR</button>


    </form>
{% endblock contenido %}



<!-- {% block js_extras %}
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script>
        $('#id_categorias').select2({
            width: '100%',
        });
    </script>
{% endblock js_extras %} -->

catalogo_productos/templates/productos/editar_categoria.html
{% extends 'base/base.html' %}


<!-- {% block css_extras %}
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
{% endblock css_extras %} -->


{% block contenido %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">            
        <h1 class="h2">Editar Categoría</h1>                       
    </div>

    <form method="POST">{% csrf_token %}



        {{form.errors}}

        {{form.as_p}}

        <hr class="my-4">
        <button class="w-100 btn btn-primary btn-lg" type="submit">GUARDAR</button>


    </form>
{% endblock contenido %}



<!-- {% block js_extras %}
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script>
        $('#id_categorias').select2({
            width: '100%',
        });
    </script>
{% endblock js_extras %} -->

catalogo_productos/templates/productos/listar.html
{% extends 'base/base.html' %}

{% load static %}

{% block contenido %}

	<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">

		<h1 class="h2">LISTA DE PRODUCTOS</h1>
		{% if messages %}

		<div class="alert alert-success" role="alert">
			<ul>
				{% for message in messages %}
					<strong>{{message}}</strong>
				{% endfor %}
			</ul>
		</div>
		
		{% endif %}

	</div>
	<div class="row">
		<div class="col">
			<form method="get">
				<div class="input-group">

					<input type="text" class="form-control" name="buscador" placeholder="Ingrese el nombre del producto para buscar" value="{{buscador}}">
					<button type="submit" class="btn btn-outline-secondary" type="button">BUSCAR</button>

				</div>
			</form>

		</div>
	</div>
	<div class="row">

		<div class="col">

			{% if user.es_admin %}
				<a href="{% url 'productos:nuevo' %}" class="btn btn-primary">Nuevo Producto</a>
				<a href="{% url 'productos:listar_categorias' %}" class="btn btn-success">Ver Categorias</a>
			{% endif %}

			<section>
				<div class="container px-4 px-lg-5 mt-5">
					<div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
						
						{% for producto in productos %}

							<div class="col mb-5">
								<div class="card h-100">
									<!-- Product image-->
									{% if producto.imagen %}
										<img src="{{producto.imagen.url}}">
									{% else %}
										<img src="{% static 'images/defaults/not-product-found.webp' %}">
									{% endif %}
									<!-- Product details-->
									<div class="card-body p-4">
										<div class="text-center">
											<!-- Product name-->
											<h5 class="fw-bolder">{{producto.nombre}}</h5>
											<!-- Product price-->
											ARS ${{producto.precio}}
										</div>
									</div>
									<!-- Product actions-->
									<div class="card-footer p-4 pt-0 border-top-0 bg-transparent">

										<div class="text-center">
											<a href="{% url 'productos:ver_detalle' producto.pk %}" class="btn btn-outline-info mt-auto"><i class="fa-solid fa-eye"></i> Ver </a>
											
											{% if user.is_authenticated and not user.es_admin %}
										
												{% if producto.pk in Favoritos %}
													
													<form class="p-3" style="display: inline-block;" action="{% url 'favoritos:quitar_favorito' producto.pk %}" method="post">
														{% csrf_token %}
														<button type="submit" class="btn btn-outline-dark mt-auto"><i class="fa-regular fa-heart"></i></i></button>
													</form>
												
												{% else %}

													<form class="p-3" style="display: inline-block;" action="{% url 'favoritos:agregar_favorito' producto.pk %}" method="post">
														{% csrf_token %}
														<button type="submit" class="btn btn-outline-danger mt-auto"><i class="fa-solid fa-heart"></i></button>
													</form>

												{% endif %}

											{% endif %}
										</div>									
										

										{% if user.is_authenticated and user.es_admin %}

										<!-- EN TEORIA ESTOS SON PARA ADMINISTRADORES -->
										<div class="text-center p-4">
											<a href="{% url 'productos:editar' producto.pk %}" class="btn btn-outline-primary btn-sm"><i class="fa-solid fa-pen-to-square"></i></a>
											<a href="{% url 'productos:eliminar' producto.pk %}" class="btn btn-outline-danger btn-sm"><i class="fa-solid fa-trash"></i> </a>
											<a href="{% url 'productos:desactivar' producto.pk %}" class="btn btn-outline-dark btn-sm"><i class="fa-solid fa-eye-slash"></i></i> </a>
										</div>
										
										{% endif %}
									</div>
								</div>
							</div>

						{% endfor %}
					</div>
				</div>
			</section>		

		</div>
	</div>
{% endblock contenido %}

catalogo_productos/templates/productos/listar_categorias.html
{% extends 'base/base.html' %}

{% block contenido %}

	<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">

		<h1 class="h2">LISTA DE CATEGORIAS</h1>


	</div>
	<div class="row">

		<div class="col">
			<a href="{% url 'productos:nueva_categoria' %}" class="btn btn-primary">Nueva Categoria</a>
			<table class="table table-striped">
				<thead>
					<tr>
						<th scope="col">ID</th>
						<th scope="col">Nombre</th>
						<th>Acciones</th>
					</tr>
				</thead>
				<tbody>

					{% for categoria in categorias %}



						<tr>
							<td>{{categoria.id}}</td>
							<td>
                                {{categoria.nombre}}
                            </td>
							<td>
								<a href="{% url 'productos:editar_categoria' categoria.pk %}" class="btn btn-primary btn-sm">EDITAR</a>
                                <a href="{% url 'productos:eliminar_categoria' categoria.pk %}" class="btn btn-danger btn-sm">ELIMINAR</i></a>
							</td>
						</tr>
					{% endfor %}

				</tbody>

			</table>

		</div>
	</div>
{% endblock contenido %}

catalogo_productos/templates/productos/producto_confirm_delete.html
{% extends 'base/base.html' %}

{% block contenido %}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">            
    <h1 class="h2">Confirmar Eliminación del Producto {{producto.nombre}} </h1>                       
</div>

<form method="POST">{% csrf_token %}
    <p><strong>¿Desea eliminar el registro {{producto.nombre}} ?</strong></p>
    <button type="submit" class="btn btn-danger">Confirmar</button>
</form>

{% endblock contenido %}

catalogo_productos/templates/productos/ver_detalle.html
{% extends 'base/base.html' %}

{% block css_extras %}
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
{% endblock css_extras %}

{% load static %}

{% block contenido %}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">            
    <h1 class="h2">Ver Detalle del Producto</h1>
    <div>
        <form style="display: inline-block;" action="{% url 'favoritos:agregar_favorito' producto.pk %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-outline-success btn-lg mt-auto"><i class="fa-solid fa-heart"></i> Agregar a Favoritos </button>
        </form>
        
        <form style="display: inline-block;" action="{% url 'favoritos:quitar_favorito' producto.pk %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-outline-danger btn-lg mt-auto"><i class="fa-regular fa-heart"></i></i> Quitar de Favoritos </button>
        </form>
    </div>
    
</div>

<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5 align-items-center">
            <div class="col-md-6">
                {% if form.instance.imagen %}
                    <img src="{{form.instance.imagen.url}}" alt="{{form.instance.nombre}}" class="img-thumbnail">
                {% else %}
                    <img src="{% static 'images/defaults/not-product-found.webp' %}">
                    <p class="text-center">No hay imagen disponible para este producto.</p>
                {% endif %}
            </div>
            <div class="col-md-6">
                {% for c in producto.categorias.all %}
                    <span class="badge rounded-pill text-bg-warning mb-3">{{c.nombre}}</span>
                {% endfor %}
                <div class="small mb-1">ID: {{form.instance.id}}</div>
                <h1 class="display-5 fw-bolder">{{form.instance.nombre}}</h1>
                <div class="fs-5 mb-5">
                    <!-- <span class="text-decoration-line-through">$45.00</span> -->
                    <span>ARS ${{form.instance.precio}}</span>
                </div>
                <p class="lead">{{form.instance.descripcion}}</p>
            </div>
        </div>
    </div>
</section>

{% endblock contenido %}


{% block js_extras %}
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script>
        $('#id_categorias').select2({
            width: '100%',
        });
    </script>
{% endblock js_extras %}