catalogo_productos/apps/usuarios/urls.py
from django.urls import path
from .views import PerfilUsuario, EditarPerfil

from . import views

app_name = "usuarios"

urlpatterns = [
    path('listar-todos/', views.listar_usuarios, name='listar_todos'),
    path('perfil/', PerfilUsuario.as_view(), name='perfil'),
    path('perfil/editar/', EditarPerfil.as_view(), name='editar_perfil'),
]

catalogo_productos/catalogo_productos/urls.py
from django.contrib import admin
from django.contrib.auth import views as views_django
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='pagina_principal'),
    path('registrarme/', views.registrarme, name="registrarme"),
    path('error-permisos/', views.pagina_error_permisos, name="error_permisos"),

    # Login & Logout
    path('login/', views_django.LoginView.as_view(template_name="login.html"), name="iniciar_sesion"),
    path('logout/', views_django.logout_then_login, name="cerrar_sesion"),
    
    # Includes
    path("usuarios/", include('apps.usuarios.urls')),
    path("productos/", include('apps.productos.urls')),
    path("favoritos/", include('apps.favoritos.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalogo_productos/apps/usuarios/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.

class Usuario(AbstractUser):
    
    biografia = models.CharField(max_length=255, null=True, blank=True)

    es_admin = models.BooleanField(default=False)

catalogo_productos/apps/usuarios/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from apps.usuarios.models import Usuario

class FormularioRegistro(forms.Form):
    username = forms.CharField(label="Nombre de usuario")
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    last_name = forms.CharField()

class FormularioRegistroUsuario(UserCreationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    last_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    first_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    password1 = forms.CharField(
        label="Contraseña",
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )

    password2 = forms.CharField(
        label="Repita contraseña",
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )

    class Meta:
        model = Usuario
        fields =  ["username", "first_name", "last_name", "email"]

    def __init__(self, *args, **kwargs):
        super(FormularioRegistroUsuario, self).__init__(*args, **kwargs)

        self.fields["email"].widget.attrs["class"] = "form-control"

class EditUser(forms.ModelForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    last_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    first_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    password1 = forms.CharField(
        label="Contraseña",
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )

    password2 = forms.CharField(
        label="Repita contraseña",
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )

    class Meta:
        model = Usuario
        fields =  ["username", "first_name", "last_name", "email"]

    def __init__(self, *args, **kwargs):
        super(EditUser, self).__init__(*args, **kwargs)

        self.fields["email"].widget.attrs["class"] = "form-control"

catalogo_productos/apps/usuarios/views.py
from django.shortcuts import render

# Create your views here.

from apps.utils.decorators import verificar_permisos
from apps.usuarios.models import Usuario

from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import DetailView, UpdateView

from .models import Usuario
from .forms import EditUser

@verificar_permisos()
def listar_usuarios(request):
    template_name = 'usuarios/listar_todos.html'
    lista_usuarios = Usuario.objects.all().order_by("id")

    ctx = {
        'usuarios': lista_usuarios,
    }
    
    return render(request, template_name, ctx)

#Perfil del Usuario
class PerfilUsuario(LoginRequiredMixin, DetailView):
    model = Usuario
    template_name = 'usuarios/perfil.html'

    def get_object(self, queryset=None):
        return self.request.user
    
#EditarPerfil

class EditarPerfil(LoginRequiredMixin, UpdateView):
    model = Usuario
    form_class = EditUser
    template_name = 'usuarios/editar_perfil.html'

    def get_object(self, queryset=None):
        return self.request.user 

    def get_success_url(self):
        return reverse_lazy('usuarios:perfil')

catalogo_productos/templates/usuarios/editar_perfil.html
{% extends 'base/base.html' %}

{% block contenido %}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
													
    <h1 class="h2">EDITAR PERFIL DE {{user.username}} </h1>                  
                                    
</div>

<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn btn-success">Guardar Cambios</button>
</form>

<a href="{% url 'usuarios:perfil' %}" class="btn btn-danger">Cancelar</a>

{% endblock contenido %}

catalogo_productos/templates/usuarios/listar_todos.html
{% extends 'base/base.html' %}

{% block contenido %}

	<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
													
		<h1 class="h2">LISTA DE USUARIOS</h1>                  
										
	</div>

	<div class="row">

		<div class="col">
			<!-- <a href="" class="btn btn-primary disabled">Nuevo usuario</a> -->
			<table class="table table-striped">
				<thead>
					<tr>
						<th scope="col">APELLIDO</th>
						<th scope="col">NOMBRE</th>
						<th scope="col">NOMBRE DE USUARIO</th>
						<th scope="col">ROLES</th>
					</tr>
				</thead>
				<tbody>
					
					{% for usuario in usuarios %}
						<tr>
							<td>{{usuario.last_name}}</td>
							<td>{{usuario.first_name}}</td>
							<td>{{usuario.username}}</td>
							<td>
								{% if usuario.es_admin %}
									<p><i class="far fa-check-circle" style="color: green"></i> ES ADMINISTRADOR</p>
								{% else %}
									<p><i class="far fa-times-circle" style="color: red"></i> NO ES ADMINISTRADOR</p>
								{% endif %}
							</td>
						</tr>
					{% empty %}
					<tr>
						<td colspan="5"><h5>No existen registros...</h5></td>
					</tr>
					{% endfor %}
					
				</tbody>

			</table>
		</div>
	</div>
{% endblock contenido %}

catalogo_productos/templates/usuarios/perfil.html
{% extends 'base/base.html' %}

{% block contenido %}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
													
    <h1 class="h2">PERFIL DEL USUARIO</h1>                  
                                    
</div>

<p><strong>Nombre:</strong> {{ user.get_full_name }}</p>
<p><strong>Correo Electrónico:</strong> {{ user.email }}</p>
{% if user.biografia %}
    <p><strong>Biografía:</strong> {{ user.biografia }}</p>
{% endif %}

<!-- <a href="#">Editar Perfil</a> -->
<a href="{% url 'usuarios:editar_perfil' %}" class="btn btn-primary btn-sm">Editar Perfil</a>


{% endblock contenido %}